language: node_js
node_js:
  - 8.5.0
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - "npm run test"
deploy:
  provider: heroku
  api_key:
    secure: 55f05f85-8553-47a3-9b6e-b344cc5da044
  app: integrador2018frontend
  on:
    repo: jdvallejor/integrador2018
